name: 'Killswitch'
description: 'Wait for execution of killswitch'
inputs:
  timeout: 
    description: 'Timeout in seconds'
    required: true
    default: '60'
outputs:
  killid:
    description: 'Id to use for kill'
runs:
  using: 'node12'
  main: 'dist/killid/index.js'
  post: 'dist/wait/index.js'
  post-if: 'success()'